model backgroundmodel
model[] models
uint64 background_refine
uint64 background_update
uint64 models_refine
---
model backgroundmodel
model[] models
image_array[] dynamicmasks
image_array[] movingmasks
